namespace GroundControl.Host.Api.Generators.WebApiModule.Emitters;

internal readonly record struct ConfigurationKeyAttributeEmitter : ISourceEmitter
{
    public string HintName => $"{KnownTypes.RootNamespace}.ConfigurationKeyAttribute.g.cs";

    public string Emit()
    {
        using var writer = new CodeWriter();

        writer
            .WriteAutoGeneratedHeader()
            .WriteNullableContextOption()
            .WriteLine()
            .WriteLine($"namespace {KnownTypes.RootNamespace};")
            .WriteLine()
            .WriteLine("/// <summary>")
            .WriteLine("/// Specifies the configuration key used to bind options for a web API module.")
            .WriteLine("/// When applied to a class, it overrides the configuration section used to bind the options.")
            .WriteLine("/// When applied to a property, it binds that property from a different configuration section.")
            .WriteLine("/// </summary>")
            .WriteGeneratedCodeAttribute()
            .WriteRaw(
                """
                [global::System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property, Inherited = false)]
                internal sealed class ConfigurationKeyAttribute : System.Attribute
                {
                    /// <summary>
                    /// Initializes a new instance of the <see cref="ConfigurationKeyAttribute"/> class.
                    /// </summary>
                    /// <param name="key">The configuration section key.</param>
                    public ConfigurationKeyAttribute(string key) => Key = key;

                    /// <summary>
                    /// Gets the configuration section key.
                    /// </summary>
                    public string Key { get; }
                }
                """);

        return writer.ToString();
    }
}