namespace GroundControl.Host.Api.Generators.WebApiModule.Emitters;

internal readonly record struct ConfigurationKeyAttributeEmitter : ISourceEmitter
{
    public string HintName => $"{KnownTypes.ApiHostNamespace}.ConfigurationKeyAttribute.g.cs";

    public string Emit()
    {
        using var writer = new CodeWriter();

        writer
            .WriteAutoGeneratedHeader()
            .WriteNullableContextOption()
            .WriteLine()
            .WriteLine($"namespace {KnownTypes.ApiHostNamespace};")
            .WriteLine()
            .WriteGeneratedCodeAttribute()
            .WriteRaw(
                """
                [global::System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
                internal sealed class ConfigurationKeyAttribute : System.Attribute
                {
                    public ConfigurationKeyAttribute(string key) => Key = key;

                    public string Key { get; }
                }
                """);

        return writer.ToString();
    }
}