namespace GroundControl.Host.Api.Generators.WebApiModule.Emitters;

internal readonly record struct ConfigurationKeyAttributeEmitter : ISourceEmitter
{
    public string HintName => $"{KnownTypes.ApiHostNamespace}.ConfigurationKeyAttribute.g.cs";

    public string Emit()
    {
        using var writer = new CodeWriter();

        writer
            .WriteAutoGeneratedHeader()
            .WriteNullableContextOption()
            .WriteLine()
            .WriteLine($"namespace {KnownTypes.ApiHostNamespace};")
            .WriteLine()
            .WriteLine("/// <summary>")
            .WriteLine("/// Specifies the configuration key used to bind options for a web API module.")
            .WriteLine("/// </summary>")
            .WriteGeneratedCodeAttribute()
            .WriteRaw(
                """
                [global::System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
                internal sealed class ConfigurationKeyAttribute : System.Attribute
                {
                    /// <summary>
                    /// Initializes a new instance of the <see cref="ConfigurationKeyAttribute"/> class.
                    /// </summary>
                    /// <param name="key">The configuration section key.</param>
                    public ConfigurationKeyAttribute(string key) => Key = key;

                    /// <summary>
                    /// Gets the configuration section key.
                    /// </summary>
                    public string Key { get; }
                }
                """);

        return writer.ToString();
    }
}