namespace GroundControl.Host.Api.Generators.WebApiModule.Emitters;

internal readonly record struct GenericWebApiModuleInterfaceEmitter : ISourceEmitter
{
    public string HintName => $"{KnownTypes.ApiHostNamespace}.IWebApiModule`1.g.cs";

    public string Emit()
    {
        using var writer = new CodeWriter();

        writer
            .WriteAutoGeneratedHeader()
            .WriteNullableContextOption()
            .WriteLine()
            .WriteRaw(
                $$"""
                namespace {{KnownTypes.ApiHostNamespace}};

                internal interface IWebApiModule<TOptions> : IWebApiModule where TOptions : class, new()
                {
                }
                """);

        return writer.ToString();
    }
}