namespace GroundControl.Host.Api.Generators.WebApiModule.Emitters;

internal readonly record struct ModuleConfigurationExceptionEmitter : ISourceEmitter
{
    public string HintName => $"{KnownTypes.ApiHostNamespace}.ModuleConfigurationException.g.cs";

    public string Emit()
    {
        using var writer = new CodeWriter();

        writer
            .WriteAutoGeneratedHeader()
            .WriteNullableContextOption()
            .WriteLine()
            .WriteLine($"namespace {KnownTypes.ApiHostNamespace};")
            .WriteLine()
            .WriteLine("/// <summary>")
            .WriteLine("/// The exception that is thrown when a web API module is incorrectly configured.")
            .WriteLine("/// </summary>")
            .WriteGeneratedCodeAttribute()
            .WriteRaw(
                """
                internal sealed class ModuleConfigurationException : System.Exception
                {
                    /// <summary>
                    /// Initializes a new instance of the <see cref="ModuleConfigurationException"/> class
                    /// with a specified error message.
                    /// </summary>
                    /// <param name="message">The message that describes the error.</param>
                    public ModuleConfigurationException(string message) : base(message)
                    {
                    }
                }
                """);

        return writer.ToString();
    }
}