namespace GroundControl.Host.Api.Generators.WebApiModule.Emitters;

internal readonly record struct RunsBeforeAttributeEmitter : ISourceEmitter
{
    public string HintName => $"{KnownTypes.RootNamespace}.RunsBeforeAttribute.g.cs";

    public string Emit()
    {
        using var writer = new CodeWriter();

        writer
            .WriteAutoGeneratedHeader()
            .WriteNullableContextOption()
            .WriteLine()
            .WriteLine($"namespace {KnownTypes.RootNamespace};")
            .WriteLine()
            .WriteLine("/// <summary>")
            .WriteLine("/// Specifies that the decorated module runs before the module of type <typeparamref name=\"T\"/>.")
            .WriteLine("/// </summary>")
            .WriteLine("/// <typeparam name=\"T\">The type of the module that must run after.</typeparam>")
            .WriteGeneratedCodeAttribute()
            .WriteRaw(
                """
                [global::System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
                internal sealed class RunsBeforeAttribute<T> : System.Attribute where T : IWebApiModule;
                """);

        return writer.ToString();
    }
}