namespace GroundControl.Host.Api.Generators.WebApiModule.Emitters;

internal readonly record struct RunsBeforeAttributeEmitter : ISourceEmitter
{
    public string HintName => $"{KnownTypes.ApiHostNamespace}.RunsBeforeAttribute.g.cs";

    public string Emit()
    {
        using var writer = new CodeWriter();

        writer
            .WriteAutoGeneratedHeader()
            .WriteNullableContextOption()
            .WriteLine()
            .WriteRaw(
                $$"""
                namespace {{KnownTypes.ApiHostNamespace}};

                [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
                internal sealed class RunsBeforeAttribute<T> : System.Attribute where T : IWebApiModule
                {
                }
                """);

        return writer.ToString();
    }
}