namespace GroundControl.Host.Api.Generators.WebApiModule.Emitters;

internal readonly record struct RunsAfterAttributeEmitter : ISourceEmitter
{
    public string HintName => $"{KnownTypes.ApiHostNamespace}.RunsAfterAttribute.g.cs";

    public string Emit()
    {
        using var writer = new CodeWriter();

        writer
            .WriteAutoGeneratedHeader()
            .WriteNullableContextOption()
            .WriteLine()
            .WriteLine($"namespace {KnownTypes.ApiHostNamespace};")
            .WriteLine()
            .WriteGeneratedCodeAttribute()
            .WriteRaw(
                """
                [global::System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
                internal sealed class RunsAfterAttribute<T> : System.Attribute where T : IWebApiModule
                {
                    public bool Required { get; init; }
                }
                """);

        return writer.ToString();
    }
}