namespace GroundControl.Host.Api.Generators.WebApiModule.Emitters;

internal readonly record struct WebApiModuleInterfaceEmitter : ISourceEmitter
{
    public string HintName => $"{KnownTypes.ApiHostNamespace}.IWebApiModule.g.cs";

    public string Emit()
    {
        using var writer = new CodeWriter();

        writer
            .WriteAutoGeneratedHeader()
            .WriteNullableContextOption()
            .WriteLine()
            .WriteRaw(
                $$"""
                namespace {{KnownTypes.ApiHostNamespace}};

                internal interface IWebApiModule
                {
                    void OnServiceConfiguration(Microsoft.AspNetCore.Builder.WebApplicationBuilder builder);

                    void OnApplicationConfiguration(Microsoft.AspNetCore.Builder.WebApplication app);
                }
                """);

        return writer.ToString();
    }
}