using System.Collections.Immutable;
using GroundControl.Host.Api.Generators.WebApiModule.Descriptors;

namespace GroundControl.Host.Api.Generators.WebApiModule.Emitters;

internal readonly record struct WebApiModuleExtensionsEmitter(
    ImmutableArray<ModuleDescriptor> SortedModules,
    ImmutableArray<OptionsValidatorDescriptor> Validators,
    string RootNamespace) : ISourceEmitter
{
    public string HintName => $"{RootNamespace}.WebApiModuleExtensions.g.cs";

    public string Emit()
    {
        var moduleMap = SortedModules.ToDictionary(m => m.FullyQualifiedName);
        var varNameMap = BuildVariableNameMap(SortedModules);
        var validatorLookup = BuildValidatorLookup(Validators);

        using var writer = new CodeWriter();

        writer
            .WriteAutoGeneratedHeader()
            .WriteNullableContextOption()
            .WriteLine()
            .WriteLine($"namespace {RootNamespace};")
            .WriteLine()
            .WriteLine("/// <summary>")
            .WriteLine("/// Provides extension methods for building and configuring web API modules.")
            .WriteLine("/// </summary>")
            .WriteGeneratedCodeAttribute()
            .WriteLine("internal static class WebApiModuleExtensions")
            .WriteOpeningBracket()
            .WriteLine("/// <summary>")
            .WriteLine("/// Builds and configures all registered web API modules.")
            .WriteLine("/// </summary>")
            .WriteLine("/// <param name=\"builder\">The web application builder.</param>")
            .WriteLine("/// <returns>The configured web application.</returns>")
            .WriteLine($"public static global::{KnownTypes.WebApplication} BuildWebApiModules(this global::{KnownTypes.WebApplicationBuilder} builder)")
            .WriteOpeningBracket();

        WriteServiceConfigurationPhase(writer, moduleMap, varNameMap, validatorLookup);

        writer
            .WriteLine()
            .WriteLine("var app = builder.Build();")
            .WriteLine();

        WriteApplicationConfigurationPhase(writer, varNameMap);

        writer
            .WriteLine()
            .WriteLine("return app;")
            .WriteClosingBracket();

        WriteIsModuleEnabledMethod(writer);

        if (SortedModules.Any(m => m.HasOptions))
        {
            WriteBindOptionsMethod(writer);
        }

        writer.WriteClosingBracket(false);

        return writer.ToString();
    }

    private void WriteServiceConfigurationPhase(
        CodeWriter writer,
        Dictionary<string, ModuleDescriptor> moduleMap,
        Dictionary<string, string> varNameMap,
        Dictionary<string, List<string>> validatorLookup)
    {
        for (var i = 0; i < SortedModules.Length; i++)
        {
            var module = SortedModules[i];
            var varName = varNameMap[module.FullyQualifiedName];
            var moduleName = GetModuleName(module.TypeName);

            writer
                .WriteLine($"{module.FullyQualifiedName}? {varName} = null;")
                .WriteLine($"if (IsModuleEnabled(builder.Configuration, \"{moduleName}\"))")
                .WriteOpeningBracket();

            WriteRequiredDependencyChecks(writer, module, moduleMap);
            WriteValidatorRegistrations(writer, module, validatorLookup);
            WriteModuleInstantiation(writer, module, varName);

            writer
                .WriteLine($"{varName}.OnServiceConfiguration(builder);")
                .WriteClosingBracket()
                .WriteNewLineIf(i < SortedModules.Length - 1);
        }
    }

    private static void WriteRequiredDependencyChecks(
        CodeWriter writer,
        ModuleDescriptor module,
        Dictionary<string, ModuleDescriptor> moduleMap)
    {
        foreach (var dep in module.RunsAfter)
        {
            if (!dep.Required || !moduleMap.TryGetValue(dep.TargetFullyQualifiedName, out var depModule))
            {
                continue;
            }

            var depModuleName = GetModuleName(depModule.TypeName);
            writer
                .WriteLine($"if (!IsModuleEnabled(builder.Configuration, \"{depModuleName}\"))")
                .WriteOpeningBracket()
                .WriteLine($"throw new global::{KnownTypes.ModuleConfigurationException}(\"Module '{module.TypeName}' requires '{depModule.TypeName}' to be enabled.\");")
                .WriteClosingBracket()
                .WriteLine();
        }
    }

    private static void WriteValidatorRegistrations(
        CodeWriter writer,
        ModuleDescriptor module,
        Dictionary<string, List<string>> validatorLookup)
    {
        if (!module.HasOptions || !validatorLookup.TryGetValue(module.OptionsTypeFullyQualifiedName!, out var validators))
        {
            return;
        }

        foreach (var validatorFqn in validators)
        {
            writer.WriteLine($"builder.Services.AddSingleton<global::{KnownTypes.ValidateOptionsInterfaceFullName}<{module.OptionsTypeFullyQualifiedName}>, {validatorFqn}>();");
        }
    }

    private static void WriteModuleInstantiation(CodeWriter writer, ModuleDescriptor module, string varName)
    {
        if (!module.HasOptions)
        {
            writer.WriteLine($"{varName} = new {module.FullyQualifiedName}();");
            return;
        }

        if (module.PropertyConfigurationOverrides.IsDefaultOrEmpty)
        {
            writer.WriteLine($"var {varName}Options = BindOptions<{module.OptionsTypeFullyQualifiedName}>(builder.Configuration, \"{module.ConfigurationSectionName}\");");
        }
        else
        {
            writer
                .WriteLine($"var {varName}Options = BindOptions<{module.OptionsTypeFullyQualifiedName}>(")
                .Indent()
                .WriteLine("builder.Configuration,")
                .WriteLine($"\"{module.ConfigurationSectionName}\",")
                .WriteLine("static (configuration, options) =>")
                .WriteOpeningBracket();

            WritePropertyConfigurationOverrides(writer, module);

            writer
                .Unindent()
                .WriteLine("});")
                .Unindent();
        }

        writer.WriteLine($"{varName} = new {module.FullyQualifiedName}({varName}Options);");
    }

    private static void WritePropertyConfigurationOverrides(CodeWriter writer, ModuleDescriptor module)
    {
        for (var i = 0; i < module.PropertyConfigurationOverrides.Length; i++)
        {
            var prop = module.PropertyConfigurationOverrides[i];

            if (prop.IsFallback)
            {
                var primaryVarName = ToCamelCase(prop.PropertyName) + "PrimarySection";
                var fallbackVarName = ToCamelCase(prop.PropertyName) + "FallbackSection";

                writer
                    .WriteLine($"var {primaryVarName} = configuration.GetSection(\"{module.ConfigurationSectionName}:{prop.PropertyName}\");")
                    .WriteLine($"if (!{primaryVarName}.Exists())")
                    .WriteOpeningBracket()
                    .WriteLine($"var {fallbackVarName} = configuration.GetSection(\"{prop.ConfigurationSectionKey}\");")
                    .WriteLine($"if ({fallbackVarName}.Exists())")
                    .WriteOpeningBracket()
                    .WriteLine($"options.{prop.PropertyName} = {fallbackVarName}.Get<{prop.PropertyTypeFullyQualifiedName}>()!;")
                    .WriteClosingBracket()
                    .WriteClosingBracket();
            }
            else
            {
                var sectionVarName = ToCamelCase(prop.PropertyName) + "Section";

                writer
                    .WriteLine($"var {sectionVarName} = configuration.GetSection(\"{prop.ConfigurationSectionKey}\");")
                    .WriteLine($"if ({sectionVarName}.Exists())")
                    .WriteOpeningBracket()
                    .WriteLine($"options.{prop.PropertyName} = {sectionVarName}.Get<{prop.PropertyTypeFullyQualifiedName}>()!;")
                    .WriteClosingBracket();
            }

            writer.WriteNewLineIf(i < module.PropertyConfigurationOverrides.Length - 1);
        }
    }

    private void WriteApplicationConfigurationPhase(CodeWriter writer, Dictionary<string, string> varNameMap) => writer
        .WriteLines(SortedModules.Select(m => $"{varNameMap[m.FullyQualifiedName]}?.OnApplicationConfiguration(app);"));

    private static void WriteIsModuleEnabledMethod(CodeWriter writer)
    {
        writer
            .WriteLine()
            .WriteLine("private static bool IsModuleEnabled(")
            .Indent()
            .WriteLine($"global::{KnownTypes.IConfiguration} configuration,")
            .WriteLine("string moduleName)")
            .Unindent()
            .WriteOpeningBracket()
            .WriteLine("return configuration.GetValue<bool?>($\"Modules:{moduleName}:Enabled\") ?? true;")
            .WriteClosingBracket();
    }

    private static void WriteBindOptionsMethod(CodeWriter writer)
    {
        writer
            .WriteLine()
            .WriteLine($"private static T BindOptions<T>(")
            .Indent()
            .WriteLine($"global::{KnownTypes.IConfiguration} configuration,")
            .WriteLine("string sectionKey,")
            .WriteLine("global::System.Action<global::Microsoft.Extensions.Configuration.IConfiguration, T>? bindPropertyOverrides = null) where T : new()")
            .Unindent()
            .WriteOpeningBracket()
            .WriteLine("var options = configuration.GetSection(sectionKey).Get<T>() ?? new T();")
            .WriteLine("bindPropertyOverrides?.Invoke(configuration, options);")
            .WriteLine("return options;")
            .WriteClosingBracket();
    }

    private static Dictionary<string, string> BuildVariableNameMap(ImmutableArray<ModuleDescriptor> modules)
    {
        var nameCount = new Dictionary<string, int>();

        foreach (var baseName in modules.Select(module => ToCamelCase(module.TypeName)))
        {
            if (nameCount.TryGetValue(baseName, out var value))
            {
                nameCount[baseName] = ++value;
            }
            else
            {
                nameCount[baseName] = 1;
            }
        }

        var result = new Dictionary<string, string>();
        var nameIndex = new Dictionary<string, int>();

        foreach (var module in modules)
        {
            var baseName = ToCamelCase(module.TypeName);

            if (nameCount[baseName] > 1)
            {
                if (!nameIndex.TryGetValue(baseName, out var value))
                {
                    value = 1;
                    nameIndex[baseName] = value;
                }

                result[module.FullyQualifiedName] = baseName + value;
                nameIndex[baseName] = ++value;
            }
            else
            {
                result[module.FullyQualifiedName] = baseName;
            }
        }

        return result;
    }

    private static string GetModuleName(string typeName)
    {
        if (typeName.Length > 6 && typeName.EndsWith("Module"))
        {
            return typeName.Substring(0, typeName.Length - 6);
        }

        return typeName;
    }

    private static string ToCamelCase(string name)
    {
        if (name.Length == 0)
        {
            return name;
        }

        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private static Dictionary<string, List<string>> BuildValidatorLookup(ImmutableArray<OptionsValidatorDescriptor> validators)
    {
        var lookup = new Dictionary<string, List<string>>();

        foreach (var validator in validators)
        {
            if (!lookup.TryGetValue(validator.OptionsTypeFullyQualifiedName, out var list))
            {
                list = [];
                lookup[validator.OptionsTypeFullyQualifiedName] = list;
            }

            list.Add(validator.ValidatorFullyQualifiedName);
        }

        return lookup;
    }
}