using System.Collections.Immutable;
using GroundControl.Host.Api.Generators.WebApiModule.Descriptors;

namespace GroundControl.Host.Api.Generators.WebApiModule.Emitters;

internal readonly record struct WebApiModuleExtensionsEmitter(
    ImmutableArray<ModuleDescriptor> SortedModules,
    string RootNamespace) : ISourceEmitter
{
    public string HintName => $"{RootNamespace}.WebApiModuleExtensions.g.cs";

    public string Emit()
    {
        var moduleMap = SortedModules.ToDictionary(m => m.FullyQualifiedName);
        var varNameMap = BuildVariableNameMap(SortedModules);

        using var writer = new CodeWriter();

        writer
            .WriteAutoGeneratedHeader()
            .WriteNullableContextOption()
            .WriteLine()
            .WriteLine($"namespace {RootNamespace};")
            .WriteLine()
            .WriteGeneratedCodeAttribute()
            .WriteLine("internal static class WebApiModuleExtensions")
            .WriteOpeningBracket()
            .WriteLine($"public static global::{KnownTypes.WebApplication} BuildWebApiModules(this global::{KnownTypes.WebApplicationBuilder} builder)")
            .WriteOpeningBracket();

        WriteServiceConfigurationPhase(writer, moduleMap, varNameMap);

        writer
            .WriteLine()
            .WriteLine("var app = builder.Build();")
            .WriteLine();

        WriteApplicationConfigurationPhase(writer, varNameMap);

        writer
            .WriteLine()
            .WriteLine("return app;")
            .WriteClosingBracket();

        WriteIsModuleEnabledMethod(writer);

        writer.WriteClosingBracket(false);

        return writer.ToString();
    }

    private void WriteServiceConfigurationPhase(
        CodeWriter writer,
        Dictionary<string, ModuleDescriptor> moduleMap,
        Dictionary<string, string> varNameMap)
    {
        for (var i = 0; i < SortedModules.Length; i++)
        {
            var module = SortedModules[i];
            var varName = varNameMap[module.FullyQualifiedName];
            var moduleName = GetModuleName(module.TypeName);

            writer
                .WriteLine($"{module.FullyQualifiedName}? {varName} = null;")
                .WriteLine($"if (IsModuleEnabled(builder.Configuration, \"{moduleName}\"))")
                .WriteOpeningBracket();

            WriteRequiredDependencyChecks(writer, module, moduleMap);
            WriteModuleInstantiation(writer, module, varName);

            writer
                .WriteLine($"{varName}.OnServiceConfiguration(builder);")
                .WriteClosingBracket()
                .WriteNewLineIf(i < SortedModules.Length - 1);
        }
    }

    private static void WriteRequiredDependencyChecks(
        CodeWriter writer,
        ModuleDescriptor module,
        Dictionary<string, ModuleDescriptor> moduleMap)
    {
        foreach (var dep in module.RunsAfter)
        {
            if (!dep.Required || !moduleMap.TryGetValue(dep.TargetFullyQualifiedName, out var depModule))
            {
                continue;
            }

            var depModuleName = GetModuleName(depModule.TypeName);
            writer
                .WriteLine($"if (!IsModuleEnabled(builder.Configuration, \"{depModuleName}\"))")
                .WriteOpeningBracket()
                .WriteLine($"throw new global::{KnownTypes.InvalidOperationException}(\"Module '{module.TypeName}' requires '{depModule.TypeName}' to be enabled.\");")
                .WriteClosingBracket()
                .WriteLine();
        }
    }

    private static void WriteModuleInstantiation(CodeWriter writer, ModuleDescriptor module, string varName)
    {
        if (module.HasOptions)
        {
            writer
                .WriteLine($"var {varName}Options = builder.Configuration")
                .Indent()
                .WriteLine($".GetSection(\"{module.ConfigurationSectionName}\")")
                .WriteLine($".Get<{module.OptionsTypeFullyQualifiedName}>() ?? new {module.OptionsTypeFullyQualifiedName}();")
                .Unindent()
                .WriteLine($"{varName} = new {module.FullyQualifiedName}({varName}Options);");
        }
        else
        {
            writer.WriteLine($"{varName} = new {module.FullyQualifiedName}();");
        }
    }

    private void WriteApplicationConfigurationPhase(CodeWriter writer, Dictionary<string, string> varNameMap)
    {
        writer.WriteLines(SortedModules.Select(m =>
            $"{varNameMap[m.FullyQualifiedName]}?.OnApplicationConfiguration(app);"));
    }

    private static void WriteIsModuleEnabledMethod(CodeWriter writer)
    {
        writer
            .WriteLine()
            .WriteLine("private static bool IsModuleEnabled(")
            .Indent()
            .WriteLine($"global::{KnownTypes.IConfiguration} configuration,")
            .WriteLine("string moduleName)")
            .Unindent()
            .WriteOpeningBracket()
            .WriteLine("return configuration.GetValue<bool?>($\"Modules:{moduleName}:Enabled\") ?? true;")
            .WriteClosingBracket();
    }

    private static Dictionary<string, string> BuildVariableNameMap(ImmutableArray<ModuleDescriptor> modules)
    {
        var nameCount = new Dictionary<string, int>();

        foreach (var baseName in modules.Select(module => ToCamelCase(module.TypeName)))
        {
            if (nameCount.TryGetValue(baseName, out var value))
            {
                nameCount[baseName] = ++value;
            }
            else
            {
                nameCount[baseName] = 1;
            }
        }

        var result = new Dictionary<string, string>();
        var nameIndex = new Dictionary<string, int>();

        foreach (var module in modules)
        {
            var baseName = ToCamelCase(module.TypeName);

            if (nameCount[baseName] > 1)
            {
                if (!nameIndex.TryGetValue(baseName, out var value))
                {
                    value = 1;
                    nameIndex[baseName] = value;
                }

                result[module.FullyQualifiedName] = baseName + value;
                nameIndex[baseName] = ++value;
            }
            else
            {
                result[module.FullyQualifiedName] = baseName;
            }
        }

        return result;
    }

    private static string GetModuleName(string typeName)
    {
        if (typeName.Length > 6 && typeName.EndsWith("Module"))
        {
            return typeName.Substring(0, typeName.Length - 6);
        }

        return typeName;
    }

    private static string ToCamelCase(string name)
    {
        if (name.Length == 0)
        {
            return name;
        }

        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}