namespace GroundControl.Host.Api.Generators.WebApiModule.Emitters;

internal readonly record struct WebApiModuleGenericInterfaceEmitter : ISourceEmitter
{
    public string HintName => $"{KnownTypes.ApiHostNamespace}.IWebApiModule`1.g.cs";

    public string Emit()
    {
        using var writer = new CodeWriter();

        writer
            .WriteAutoGeneratedHeader()
            .WriteNullableContextOption()
            .WriteLine()
            .WriteLine($"namespace {KnownTypes.ApiHostNamespace};")
            .WriteLine()
            .WriteLine("/// <summary>")
            .WriteLine("/// Defines a web API module that requires strongly-typed options bound from configuration.")
            .WriteLine("/// </summary>")
            .WriteLine("/// <typeparam name=\"TOptions\">The options type bound from configuration.</typeparam>")
            .WriteGeneratedCodeAttribute()
            .WriteRaw(
                $"internal interface IWebApiModule<TOptions> : global::{KnownTypes.ApiHostNamespace}.IWebApiModule where TOptions : class, new();");

        return writer.ToString();
    }
}