namespace GroundControl.Host.Api.Generators.WebApiModule.Emitters;

internal readonly record struct WebApiModuleInterfaceEmitter : ISourceEmitter
{
    public string HintName => $"{KnownTypes.ApiHostNamespace}.IWebApiModule.g.cs";

    public string Emit()
    {
        using var writer = new CodeWriter();

        writer
            .WriteAutoGeneratedHeader()
            .WriteNullableContextOption()
            .WriteLine()
            .WriteLine($"namespace {KnownTypes.ApiHostNamespace};")
            .WriteLine()
            .WriteGeneratedCodeAttribute()
            .WriteRaw(
                $$"""
                internal interface IWebApiModule
                {
                    void OnServiceConfiguration(global::{{KnownTypes.WebApplicationBuilder}} builder);

                    void OnApplicationConfiguration(global::{{KnownTypes.WebApplication}} app);
                }
                """);

        return writer.ToString();
    }
}