//HintName: TestAssembly.WebApiModuleExtensions.g.cs
// <auto-generated />
#nullable enable

namespace TestAssembly;

/// <summary>
/// Provides extension methods for building and configuring web API modules.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""GroundControl.Host.Api.Generators", "1.0.0.0"")]
internal static class WebApiModuleExtensions
{
    /// <summary>
    /// Builds and configures all registered web API modules.
    /// </summary>
    /// <param name="builder">The web application builder.</param>
    /// <returns>The configured web application.</returns>
    public static global::Microsoft.AspNetCore.Builder.WebApplication BuildWebApiModules(this global::Microsoft.AspNetCore.Builder.WebApplicationBuilder builder)
    {
        global::LoggingModule? loggingModule = null;
        if (IsModuleEnabled(builder.Configuration, "Logging"))
        {
            loggingModule = new global::LoggingModule();
            ((global::GroundControl.Host.Api.IWebApiModule)loggingModule).OnServiceConfiguration(builder);
        }
        
        global::AuthModule? authModule = null;
        if (IsModuleEnabled(builder.Configuration, "Auth"))
        {
            var authModuleOptions = BindOptions<global::AuthOptions>(builder.Configuration, "Auth");
            authModule = new global::AuthModule(authModuleOptions);
            ((global::GroundControl.Host.Api.IWebApiModule)authModule).OnServiceConfiguration(builder);
        }
        
        global::CacheModule? cacheModule = null;
        if (IsModuleEnabled(builder.Configuration, "Cache"))
        {
            var cacheModuleOptions = BindOptions<global::CacheConfig>(builder.Configuration, "CacheConfig");
            cacheModule = new global::CacheModule(cacheModuleOptions);
            ((global::GroundControl.Host.Api.IWebApiModule)cacheModule).OnServiceConfiguration(builder);
        }
        
        global::ApiModule? apiModule = null;
        if (IsModuleEnabled(builder.Configuration, "Api"))
        {
            apiModule = new global::ApiModule();
            ((global::GroundControl.Host.Api.IWebApiModule)apiModule).OnServiceConfiguration(builder);
        }

        var app = builder.Build();

        (loggingModule as global::GroundControl.Host.Api.IWebApiModule)?.OnApplicationConfiguration(app);
        (authModule as global::GroundControl.Host.Api.IWebApiModule)?.OnApplicationConfiguration(app);
        (cacheModule as global::GroundControl.Host.Api.IWebApiModule)?.OnApplicationConfiguration(app);
        (apiModule as global::GroundControl.Host.Api.IWebApiModule)?.OnApplicationConfiguration(app);

        return app;
    }

    private static bool IsModuleEnabled(
        global::Microsoft.Extensions.Configuration.IConfiguration configuration,
        string moduleName)
    {
        return configuration.GetValue<bool?>($"Modules:{moduleName}:Enabled") ?? true;
    }

    private static T BindOptions<T>(
        global::Microsoft.Extensions.Configuration.IConfiguration configuration,
        string sectionKey,
        global::System.Action<global::Microsoft.Extensions.Configuration.IConfiguration, T>? bindPropertyOverrides = null) where T : new()
    {
        var options = configuration.GetSection(sectionKey).Get<T>() ?? new T();
        bindPropertyOverrides?.Invoke(configuration, options);
        return options;
    }
}