//HintName: TestAssembly.WebApiModuleExtensions.g.cs
// <auto-generated />
#nullable enable

namespace TestAssembly;

/// <summary>
/// Provides extension methods for building and configuring web API modules.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""GroundControl.Host.Api.Generators", "1.0.0.0"")]
internal static class WebApiModuleExtensions
{
    /// <summary>
    /// Builds and configures all registered web API modules.
    /// </summary>
    /// <param name="builder">The web application builder.</param>
    /// <returns>The configured web application.</returns>
    public static global::Microsoft.AspNetCore.Builder.WebApplication BuildWebApiModules(this global::Microsoft.AspNetCore.Builder.WebApplicationBuilder builder)
    {
        global::ConfigModule? configModule = null;
        if (IsModuleEnabled(builder.Configuration, "Config"))
        {
            configModule = new global::ConfigModule();
            ((global::GroundControl.Host.Api.IWebApiModule)configModule).OnServiceConfiguration(builder);
        }
        
        global::DatabaseModule? databaseModule = null;
        if (IsModuleEnabled(builder.Configuration, "Database"))
        {
            databaseModule = new global::DatabaseModule();
            ((global::GroundControl.Host.Api.IWebApiModule)databaseModule).OnServiceConfiguration(builder);
        }
        
        global::HealthChecksModule? healthChecksModule = null;
        if (IsModuleEnabled(builder.Configuration, "HealthChecks"))
        {
            healthChecksModule = new global::HealthChecksModule();
            ((global::GroundControl.Host.Api.IWebApiModule)healthChecksModule).OnServiceConfiguration(builder);
        }
        
        global::LoggingModule? loggingModule = null;
        if (IsModuleEnabled(builder.Configuration, "Logging"))
        {
            loggingModule = new global::LoggingModule();
            ((global::GroundControl.Host.Api.IWebApiModule)loggingModule).OnServiceConfiguration(builder);
        }
        
        global::AuthModule? authModule = null;
        if (IsModuleEnabled(builder.Configuration, "Auth"))
        {
            authModule = new global::AuthModule();
            ((global::GroundControl.Host.Api.IWebApiModule)authModule).OnServiceConfiguration(builder);
        }
        
        global::ApiModule? apiModule = null;
        if (IsModuleEnabled(builder.Configuration, "Api"))
        {
            apiModule = new global::ApiModule();
            ((global::GroundControl.Host.Api.IWebApiModule)apiModule).OnServiceConfiguration(builder);
        }

        var app = builder.Build();

        (configModule as global::GroundControl.Host.Api.IWebApiModule)?.OnApplicationConfiguration(app);
        (databaseModule as global::GroundControl.Host.Api.IWebApiModule)?.OnApplicationConfiguration(app);
        (healthChecksModule as global::GroundControl.Host.Api.IWebApiModule)?.OnApplicationConfiguration(app);
        (loggingModule as global::GroundControl.Host.Api.IWebApiModule)?.OnApplicationConfiguration(app);
        (authModule as global::GroundControl.Host.Api.IWebApiModule)?.OnApplicationConfiguration(app);
        (apiModule as global::GroundControl.Host.Api.IWebApiModule)?.OnApplicationConfiguration(app);

        return app;
    }

    private static bool IsModuleEnabled(
        global::Microsoft.Extensions.Configuration.IConfiguration configuration,
        string moduleName)
    {
        return configuration.GetValue<bool?>($"Modules:{moduleName}:Enabled") ?? true;
    }
}