//HintName: TestAssembly.WebApiModuleExtensions.g.cs
// <auto-generated />
#nullable enable

namespace TestAssembly;

/// <summary>
/// Provides extension methods for building and configuring web API modules.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""GroundControl.Host.Api.Generators", "1.0.0.0"")]
internal static class WebApiModuleExtensions
{
    /// <summary>
    /// Builds and configures all registered web API modules.
    /// </summary>
    /// <param name="builder">The web application builder.</param>
    /// <returns>The configured web application.</returns>
    public static global::Microsoft.AspNetCore.Builder.WebApplication BuildWebApiModules(this global::Microsoft.AspNetCore.Builder.WebApplicationBuilder builder)
    {
        global::CoreModule? coreModule = null;
        if (IsModuleEnabled(builder.Configuration, "Core"))
        {
            coreModule = new global::CoreModule();
            coreModule.OnServiceConfiguration(builder);
        }
        
        global::DatabaseModule? databaseModule = null;
        if (IsModuleEnabled(builder.Configuration, "Database"))
        {
            var databaseModuleOptions = builder.Configuration
                .GetSection("Database")
                .Get<global::DatabaseOptions>() ?? new global::DatabaseOptions();
            databaseModule = new global::DatabaseModule(databaseModuleOptions);
            databaseModule.OnServiceConfiguration(builder);
        }
        
        global::MigrationModule? migrationModule = null;
        if (IsModuleEnabled(builder.Configuration, "Migration"))
        {
            migrationModule = new global::MigrationModule();
            migrationModule.OnServiceConfiguration(builder);
        }
        
        global::ObservabilityModule? observabilityModule = null;
        if (IsModuleEnabled(builder.Configuration, "Observability"))
        {
            var observabilityModuleOptions = builder.Configuration
                .GetSection("Telemetry")
                .Get<global::ObservabilityOptions>() ?? new global::ObservabilityOptions();
            observabilityModule = new global::ObservabilityModule(observabilityModuleOptions);
            observabilityModule.OnServiceConfiguration(builder);
        }
        
        global::ApiModule? apiModule = null;
        if (IsModuleEnabled(builder.Configuration, "Api"))
        {
            if (!IsModuleEnabled(builder.Configuration, "Database"))
            {
                throw new global::System.InvalidOperationException("Module 'ApiModule' requires 'DatabaseModule' to be enabled.");
            }

            apiModule = new global::ApiModule();
            apiModule.OnServiceConfiguration(builder);
        }

        var app = builder.Build();

        coreModule?.OnApplicationConfiguration(app);
        databaseModule?.OnApplicationConfiguration(app);
        migrationModule?.OnApplicationConfiguration(app);
        observabilityModule?.OnApplicationConfiguration(app);
        apiModule?.OnApplicationConfiguration(app);

        return app;
    }

    private static bool IsModuleEnabled(
        global::Microsoft.Extensions.Configuration.IConfiguration configuration,
        string moduleName)
    {
        return configuration.GetValue<bool?>($"Modules:{moduleName}:Enabled") ?? true;
    }
}