//HintName: TestAssembly.WebApiModuleExtensions.g.cs
// <auto-generated />
#nullable enable

namespace TestAssembly;

/// <summary>
/// Provides extension methods for building and configuring web API modules.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""GroundControl.Host.Api.Generators", "1.0.0.0"")]
internal static class WebApiModuleExtensions
{
    /// <summary>
    /// Builds and configures all registered web API modules.
    /// </summary>
    /// <param name="builder">The web application builder.</param>
    /// <returns>The configured web application.</returns>
    public static global::Microsoft.AspNetCore.Builder.WebApplication BuildWebApiModules(this global::Microsoft.AspNetCore.Builder.WebApplicationBuilder builder)
    {
        global::GroundControl.Host.Api.IWebApiModule? configModule = null;
        if (IsModuleEnabled(builder.Configuration, "Config"))
        {
            configModule = new global::ConfigModule();
            configModule.OnServiceConfiguration(builder);
        }
        
        global::GroundControl.Host.Api.IWebApiModule? databaseModule = null;
        if (IsModuleEnabled(builder.Configuration, "Database"))
        {
            databaseModule = new global::DatabaseModule();
            databaseModule.OnServiceConfiguration(builder);
        }
        
        global::GroundControl.Host.Api.IWebApiModule? healthChecksModule = null;
        if (IsModuleEnabled(builder.Configuration, "HealthChecks"))
        {
            healthChecksModule = new global::HealthChecksModule();
            healthChecksModule.OnServiceConfiguration(builder);
        }
        
        global::GroundControl.Host.Api.IWebApiModule? loggingModule = null;
        if (IsModuleEnabled(builder.Configuration, "Logging"))
        {
            loggingModule = new global::LoggingModule();
            loggingModule.OnServiceConfiguration(builder);
        }
        
        global::GroundControl.Host.Api.IWebApiModule? authModule = null;
        if (IsModuleEnabled(builder.Configuration, "Auth"))
        {
            authModule = new global::AuthModule();
            authModule.OnServiceConfiguration(builder);
        }
        
        global::GroundControl.Host.Api.IWebApiModule? apiModule = null;
        if (IsModuleEnabled(builder.Configuration, "Api"))
        {
            apiModule = new global::ApiModule();
            apiModule.OnServiceConfiguration(builder);
        }

        var app = builder.Build();

        configModule?.OnApplicationConfiguration(app);
        databaseModule?.OnApplicationConfiguration(app);
        healthChecksModule?.OnApplicationConfiguration(app);
        loggingModule?.OnApplicationConfiguration(app);
        authModule?.OnApplicationConfiguration(app);
        apiModule?.OnApplicationConfiguration(app);

        return app;
    }

    private static bool IsModuleEnabled(
        global::Microsoft.Extensions.Configuration.IConfiguration configuration,
        string moduleName)
    {
        return configuration.GetValue<bool?>($"Modules:{moduleName}:Enabled") ?? true;
    }
}