//HintName: TestAssembly.WebApiModuleExtensions.g.cs
// <auto-generated />
#nullable enable

namespace TestAssembly;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""GroundControl.Host.Api.Generators", "1.0.0.0"")]
internal static class WebApiModuleExtensions
{
    public static global::Microsoft.AspNetCore.Builder.WebApplication BuildWebApiModules(this global::Microsoft.AspNetCore.Builder.WebApplicationBuilder builder)
    {
        global::MyModule? myModule = null;
        if (IsModuleEnabled(builder.Configuration, "My"))
        {
            var myModuleOptions = builder.Configuration
                .GetSection("CustomKey")
                .Get<global::MyOptions>() ?? new global::MyOptions();
            myModule = new global::MyModule(myModuleOptions);
            myModule.OnServiceConfiguration(builder);
        }

        var app = builder.Build();

        myModule?.OnApplicationConfiguration(app);

        return app;
    }

    private static bool IsModuleEnabled(
        global::Microsoft.Extensions.Configuration.IConfiguration configuration,
        string moduleName)
    {
        return configuration.GetValue<bool?>($"Modules:{moduleName}:Enabled") ?? true;
    }
}