//HintName: TestAssembly.WebApiModuleExtensions.g.cs
// <auto-generated />
#nullable enable

namespace TestAssembly;

/// <summary>
/// Provides extension methods for building and configuring web API modules.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""GroundControl.Host.Api.Generators", "1.0.0.0"")]
internal static class WebApiModuleExtensions
{
    /// <summary>
    /// Builds and configures all registered web API modules.
    /// </summary>
    /// <param name="builder">The web application builder.</param>
    /// <returns>The configured web application.</returns>
    public static global::Microsoft.AspNetCore.Builder.WebApplication BuildWebApiModules(this global::Microsoft.AspNetCore.Builder.WebApplicationBuilder builder)
    {
        global::FooModule? fooModule = null;
        if (IsModuleEnabled(builder.Configuration, "Foo"))
        {
            var fooModuleOptions = builder.Configuration
                .GetSection("Options")
                .Get<global::Options>() ?? new global::Options();
            fooModule = new global::FooModule(fooModuleOptions);
            fooModule.OnServiceConfiguration(builder);
        }

        var app = builder.Build();

        fooModule?.OnApplicationConfiguration(app);

        return app;
    }

    private static bool IsModuleEnabled(
        global::Microsoft.Extensions.Configuration.IConfiguration configuration,
        string moduleName)
    {
        return configuration.GetValue<bool?>($"Modules:{moduleName}:Enabled") ?? true;
    }
}