//HintName: TestAssembly.WebApiModuleExtensions.g.cs
// <auto-generated />
#nullable enable

namespace TestAssembly;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""GroundControl.Host.Api.Generators", "1.0.0.0"")]
internal static class WebApiModuleExtensions
{
    public static global::Microsoft.AspNetCore.Builder.WebApplication BuildWebApiModules(this global::Microsoft.AspNetCore.Builder.WebApplicationBuilder builder)
    {
        global::ModuleD? moduleD = null;
        if (IsModuleEnabled(builder.Configuration, "ModuleD"))
        {
            moduleD = new global::ModuleD();
            moduleD.OnServiceConfiguration(builder);
        }
        
        global::ModuleB? moduleB = null;
        if (IsModuleEnabled(builder.Configuration, "ModuleB"))
        {
            moduleB = new global::ModuleB();
            moduleB.OnServiceConfiguration(builder);
        }
        
        global::ModuleC? moduleC = null;
        if (IsModuleEnabled(builder.Configuration, "ModuleC"))
        {
            moduleC = new global::ModuleC();
            moduleC.OnServiceConfiguration(builder);
        }
        
        global::ModuleA? moduleA = null;
        if (IsModuleEnabled(builder.Configuration, "ModuleA"))
        {
            moduleA = new global::ModuleA();
            moduleA.OnServiceConfiguration(builder);
        }

        var app = builder.Build();

        moduleD?.OnApplicationConfiguration(app);
        moduleB?.OnApplicationConfiguration(app);
        moduleC?.OnApplicationConfiguration(app);
        moduleA?.OnApplicationConfiguration(app);

        return app;
    }

    private static bool IsModuleEnabled(
        global::Microsoft.Extensions.Configuration.IConfiguration configuration,
        string moduleName)
    {
        return configuration.GetValue<bool?>($"Modules:{moduleName}:Enabled") ?? true;
    }
}