//HintName: TestAssembly.WebApiModuleExtensions.g.cs
// <auto-generated />
#nullable enable

namespace TestAssembly;

/// <summary>
/// Provides extension methods for building and configuring web API modules.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""GroundControl.Host.Api.Generators", "1.0.0.0"")]
internal static class WebApiModuleExtensions
{
    /// <summary>
    /// Builds and configures all registered web API modules.
    /// </summary>
    /// <param name="builder">The web application builder.</param>
    /// <returns>The configured web application.</returns>
    public static global::Microsoft.AspNetCore.Builder.WebApplication BuildWebApiModules(this global::Microsoft.AspNetCore.Builder.WebApplicationBuilder builder)
    {
        global::GroundControl.Host.Api.IWebApiModule? middleModule = null;
        if (IsModuleEnabled(builder.Configuration, "Middle"))
        {
            middleModule = new global::MiddleModule();
            middleModule.OnServiceConfiguration(builder);
        }
        
        global::GroundControl.Host.Api.IWebApiModule? zzzModule = null;
        if (IsModuleEnabled(builder.Configuration, "Zzz"))
        {
            zzzModule = new global::ZzzModule();
            zzzModule.OnServiceConfiguration(builder);
        }
        
        global::GroundControl.Host.Api.IWebApiModule? aaaModule = null;
        if (IsModuleEnabled(builder.Configuration, "Aaa"))
        {
            aaaModule = new global::AaaModule();
            aaaModule.OnServiceConfiguration(builder);
        }

        var app = builder.Build();

        middleModule?.OnApplicationConfiguration(app);
        zzzModule?.OnApplicationConfiguration(app);
        aaaModule?.OnApplicationConfiguration(app);

        return app;
    }

    private static bool IsModuleEnabled(
        global::Microsoft.Extensions.Configuration.IConfiguration configuration,
        string moduleName)
    {
        return configuration.GetValue<bool?>($"Modules:{moduleName}:Enabled") ?? true;
    }
}