//HintName: TestAssembly.WebApiModuleExtensions.g.cs
// <auto-generated />
#nullable enable

namespace TestAssembly;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""GroundControl.Host.Api.Generators", "1.0.0.0"")]
internal static class WebApiModuleExtensions
{
    public static global::Microsoft.AspNetCore.Builder.WebApplication BuildWebApiModules(this global::Microsoft.AspNetCore.Builder.WebApplicationBuilder builder)
    {
        global::AlphaModule? alphaModule = null;
        if (IsModuleEnabled(builder.Configuration, "Alpha"))
        {
            alphaModule = new global::AlphaModule();
            alphaModule.OnServiceConfiguration(builder);
        }
        
        global::ZebraModule? zebraModule = null;
        if (IsModuleEnabled(builder.Configuration, "Zebra"))
        {
            zebraModule = new global::ZebraModule();
            zebraModule.OnServiceConfiguration(builder);
        }

        var app = builder.Build();

        alphaModule?.OnApplicationConfiguration(app);
        zebraModule?.OnApplicationConfiguration(app);

        return app;
    }

    private static bool IsModuleEnabled(
        global::Microsoft.Extensions.Configuration.IConfiguration configuration,
        string moduleName)
    {
        return configuration.GetValue<bool?>($"Modules:{moduleName}:Enabled") ?? true;
    }
}