//HintName: TestAssembly.WebApiModuleExtensions.g.cs
// <auto-generated />
#nullable enable

namespace TestAssembly;

/// <summary>
/// Provides extension methods for building and configuring web API modules.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""GroundControl.Host.Api.Generators", "1.0.0.0"")]
internal static class WebApiModuleExtensions
{
    /// <summary>
    /// Builds and configures all registered web API modules.
    /// </summary>
    /// <param name="builder">The web application builder.</param>
    /// <returns>The configured web application.</returns>
    public static global::Microsoft.AspNetCore.Builder.WebApplication BuildWebApiModules(this global::Microsoft.AspNetCore.Builder.WebApplicationBuilder builder)
    {
        global::GroundControl.Host.Api.IWebApiModule? myModule = null;
        if (IsModuleEnabled(builder.Configuration, "My"))
        {
            builder.Services.AddSingleton<global::Microsoft.Extensions.Options.IValidateOptions<global::MyOptions>, global::MyOptions.Validator>();
            var myModuleOptions = BindOptions<global::MyOptions>(builder.Configuration, "My");
            myModule = new global::MyModule(myModuleOptions);
            myModule.OnServiceConfiguration(builder);
        }

        var app = builder.Build();

        myModule?.OnApplicationConfiguration(app);

        return app;
    }

    private static bool IsModuleEnabled(
        global::Microsoft.Extensions.Configuration.IConfiguration configuration,
        string moduleName)
    {
        return configuration.GetValue<bool?>($"Modules:{moduleName}:Enabled") ?? true;
    }

    private static T BindOptions<T>(
        global::Microsoft.Extensions.Configuration.IConfiguration configuration,
        string sectionKey,
        global::System.Action<global::Microsoft.Extensions.Configuration.IConfiguration, T>? bindPropertyOverrides = null) where T : new()
    {
        var options = configuration.GetSection(sectionKey).Get<T>() ?? new T();
        bindPropertyOverrides?.Invoke(configuration, options);
        return options;
    }
}