using Microsoft.CodeAnalysis.CSharp;

namespace GroundControl.Host.Api.Generators.Internals.Generators;

internal static class CodeWriterExtensions
{
    extension(CodeWriter src)
    {
        public CodeWriter Wrap(CodeWriter writer) => writer;

        public CodeWriter WriteAllowNullAttribute() =>
            src.Write("[global::System.Diagnostics.CodeAnalysis.AllowNull] ");

        public CodeWriter WriteAllowNullAttributeIf(bool condition) =>
            condition ? src.WriteAllowNullAttribute() : src;

        public CodeWriter WriteAutoGeneratedHeader() =>
            src.WriteLine("// <auto-generated />");

        public CodeWriter WriteAutoGeneratedHeaderIf(bool condition) =>
            condition ? src.WriteAutoGeneratedHeader() : src;

        public CodeWriter WriteGeneratedCodeAttribute() =>
            src.WriteLine($@"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{ThisAssembly.AssemblyName}"", ""{ThisAssembly.AssemblyFileVersion}"")]");

        public CodeWriter WriteIsNotNullCheck(string parameterName) => src.LanguageVersion switch
        {
            < LanguageVersion.CSharp7 => src.Write($"!ReferenceEquals({parameterName}, null)"),
            < LanguageVersion.CSharp9 => src.Write($"!({parameterName} is not null)"),
            _ => src.Write($"{parameterName} is not null")
        };

        public CodeWriter WriteIsNullCheck(string parameterName) =>
            src.Write(src.LanguageVersion >= LanguageVersion.CSharp7 ? $"{parameterName} is null" : $"ReferenceEquals({parameterName}, null)");

        public CodeWriter WriteLineComment(string comment) =>
            src.WriteLine($"// {comment}");

        public CodeWriter WriteNullableContextOption() => src.WriteNullableContextOptionIf(true);

        public CodeWriter WriteNullableContextOptionIf(bool enabled) =>
            src.WriteLineIf(enabled, "#nullable enable");

        public CodeWriter WriteReturnNotNullIfNotNullAttribute(string parameterName) =>
            src.WriteLine($"""[return: global::System.Diagnostics.CodeAnalysis.NotNullIfNotNull("{parameterName}")]""");

        public CodeWriter WriteReturnNotNullIfNotNullAttributeIf(bool condition, string parameterName) =>
            condition ? src.WriteReturnNotNullIfNotNullAttribute(parameterName) : src;

        public CodeWriter WriteSuppressFileScopeCompilerWarning(string id, string? comment = null) =>
            src.Write($"#pragma warning disable {id}").WriteLineIf(comment is not null, $" // {comment}");

        public CodeWriter WriteSuppressFileScopeCompilerWarningIf(bool condition, string id, string? comment = null) =>
            condition ? src.WriteSuppressFileScopeCompilerWarning(id, comment) : src;

        public CodeWriter WriteTernaryArgumentNullCheck(string parameterName, string trueValue) =>
            src.WriteIsNullCheck(parameterName).Write(" ? ").WriteThrowArgumentNullException(parameterName).Write(" : ").Write(trueValue);

        public CodeWriter WriteTernaryArgumentNullCheckIf(bool condition, string parameterName, string trueValue) =>
            condition ? src.WriteTernaryArgumentNullCheck(parameterName, trueValue) : src;

        public CodeWriter WriteTernaryIsNotNullCheck(string parameterName, string trueValue, string falseValue) =>
            src.WriteIsNotNullCheck(parameterName).Write($" ? {trueValue} : {falseValue}");

        public CodeWriter WriteTernaryIsNullCheck(string parameterName, string trueValue, string falseValue) =>
            src.WriteIsNullCheck(parameterName).Write(" ? ").Write(trueValue).Write(" : ").Write(falseValue);

        public CodeWriter WriteThrowArgumentNullException(string parameterName) =>
            src.Write($"throw new global::{KnownTypes.ArgumentNullException}(nameof({parameterName}))");

        public CodeWriter WriteThrowArgumentOutOfRangeException(string source, string message) => src.WriteThrowArgumentOutOfRangeException(source, source, message);

        public CodeWriter WriteThrowArgumentOutOfRangeException(string parameterName, string source, string message) =>
            src.Write($"throw new global::{KnownTypes.ArgumentOutOfRangeException}(\"{parameterName}\", {source}, {message})");

        public CodeWriter WriteThrowInvalidOperationException(string message) =>
            src.WriteLine($"throw new global::{KnownTypes.InvalidOperationException}(\"{message}\");");

        public CodeWriter WriteThrowNotImplementedException() =>
            src.Write("throw new System.NotImplementedException()");

        public CodeWriter WriteUsing(string u) =>
            src.WriteLine($"using {u};");

        public CodeWriter WriteUsings(IEnumerable<string>? usings)
        {
            if (usings is null)
            {
                return src;
            }

            var hasUsings = false;
            foreach (var u in usings.OrderBy(s => s))
            {
                src.WriteUsing(u);
                hasUsings = true;
            }

            return src.WriteLineIf(hasUsings);
        }
    }
}