namespace GroundControl.Host.Api.Generators.WebApiModule.Descriptors;

internal readonly record struct OptionsValidatorDescriptor(string ValidatorFullyQualifiedName, string OptionsTypeFullyQualifiedName);