/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VariablesRouteImport } from './routes/variables'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ScopesRouteImport } from './routes/scopes'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTokensRouteImport } from './routes/admin/tokens'
import { Route as AdminGroupsRouteImport } from './routes/admin/groups'
import { Route as ProjectsProjectIdRouteRouteImport } from './routes/projects/$projectId/route'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as AdminGroupsIndexRouteImport } from './routes/admin/groups.index'
import { Route as ProjectsGroupGroupIdRouteImport } from './routes/projects/group/$groupId'
import { Route as ProjectsProjectIdSnapshotsRouteImport } from './routes/projects/$projectId/snapshots'
import { Route as ProjectsProjectIdConfigRouteImport } from './routes/projects/$projectId/config'
import { Route as ProjectsProjectIdClientsRouteImport } from './routes/projects/$projectId/clients'
import { Route as AdminGroupsGroupIdRouteImport } from './routes/admin/groups.$groupId'

const VariablesRoute = VariablesRouteImport.update({
  id: '/variables',
  path: '/variables',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopesRoute = ScopesRouteImport.update({
  id: '/scopes',
  path: '/scopes',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTokensRoute = AdminTokensRouteImport.update({
  id: '/admin/tokens',
  path: '/admin/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/admin/groups',
  path: '/admin/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRouteRoute = ProjectsProjectIdRouteRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const AdminGroupsIndexRoute = AdminGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminGroupsRoute,
} as any)
const ProjectsGroupGroupIdRoute = ProjectsGroupGroupIdRouteImport.update({
  id: '/projects/group/$groupId',
  path: '/projects/group/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdSnapshotsRoute =
  ProjectsProjectIdSnapshotsRouteImport.update({
    id: '/snapshots',
    path: '/snapshots',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdConfigRoute = ProjectsProjectIdConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectsProjectIdClientsRoute =
  ProjectsProjectIdClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const AdminGroupsGroupIdRoute = AdminGroupsGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => AdminGroupsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/clients': typeof ClientsRoute
  '/overview': typeof OverviewRoute
  '/scopes': typeof ScopesRoute
  '/templates': typeof TemplatesRoute
  '/variables': typeof VariablesRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/admin/groups': typeof AdminGroupsRouteWithChildren
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/users': typeof AdminUsersRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/groups/$groupId': typeof AdminGroupsGroupIdRoute
  '/projects/$projectId/clients': typeof ProjectsProjectIdClientsRoute
  '/projects/$projectId/config': typeof ProjectsProjectIdConfigRoute
  '/projects/$projectId/snapshots': typeof ProjectsProjectIdSnapshotsRoute
  '/projects/group/$groupId': typeof ProjectsGroupGroupIdRoute
  '/admin/groups/': typeof AdminGroupsIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/clients': typeof ClientsRoute
  '/overview': typeof OverviewRoute
  '/scopes': typeof ScopesRoute
  '/templates': typeof TemplatesRoute
  '/variables': typeof VariablesRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/users': typeof AdminUsersRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/groups/$groupId': typeof AdminGroupsGroupIdRoute
  '/projects/$projectId/clients': typeof ProjectsProjectIdClientsRoute
  '/projects/$projectId/config': typeof ProjectsProjectIdConfigRoute
  '/projects/$projectId/snapshots': typeof ProjectsProjectIdSnapshotsRoute
  '/projects/group/$groupId': typeof ProjectsGroupGroupIdRoute
  '/admin/groups': typeof AdminGroupsIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/clients': typeof ClientsRoute
  '/overview': typeof OverviewRoute
  '/scopes': typeof ScopesRoute
  '/templates': typeof TemplatesRoute
  '/variables': typeof VariablesRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/admin/groups': typeof AdminGroupsRouteWithChildren
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/users': typeof AdminUsersRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/groups/$groupId': typeof AdminGroupsGroupIdRoute
  '/projects/$projectId/clients': typeof ProjectsProjectIdClientsRoute
  '/projects/$projectId/config': typeof ProjectsProjectIdConfigRoute
  '/projects/$projectId/snapshots': typeof ProjectsProjectIdSnapshotsRoute
  '/projects/group/$groupId': typeof ProjectsGroupGroupIdRoute
  '/admin/groups/': typeof AdminGroupsIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/clients'
    | '/overview'
    | '/scopes'
    | '/templates'
    | '/variables'
    | '/projects/$projectId'
    | '/admin/groups'
    | '/admin/tokens'
    | '/admin/users'
    | '/projects/'
    | '/admin/groups/$groupId'
    | '/projects/$projectId/clients'
    | '/projects/$projectId/config'
    | '/projects/$projectId/snapshots'
    | '/projects/group/$groupId'
    | '/admin/groups/'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/clients'
    | '/overview'
    | '/scopes'
    | '/templates'
    | '/variables'
    | '/admin/tokens'
    | '/admin/users'
    | '/projects'
    | '/admin/groups/$groupId'
    | '/projects/$projectId/clients'
    | '/projects/$projectId/config'
    | '/projects/$projectId/snapshots'
    | '/projects/group/$groupId'
    | '/admin/groups'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/clients'
    | '/overview'
    | '/scopes'
    | '/templates'
    | '/variables'
    | '/projects/$projectId'
    | '/admin/groups'
    | '/admin/tokens'
    | '/admin/users'
    | '/projects/'
    | '/admin/groups/$groupId'
    | '/projects/$projectId/clients'
    | '/projects/$projectId/config'
    | '/projects/$projectId/snapshots'
    | '/projects/group/$groupId'
    | '/admin/groups/'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  ClientsRoute: typeof ClientsRoute
  OverviewRoute: typeof OverviewRoute
  ScopesRoute: typeof ScopesRoute
  TemplatesRoute: typeof TemplatesRoute
  VariablesRoute: typeof VariablesRoute
  ProjectsProjectIdRouteRoute: typeof ProjectsProjectIdRouteRouteWithChildren
  AdminGroupsRoute: typeof AdminGroupsRouteWithChildren
  AdminTokensRoute: typeof AdminTokensRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsGroupGroupIdRoute: typeof ProjectsGroupGroupIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/variables': {
      id: '/variables'
      path: '/variables'
      fullPath: '/variables'
      preLoaderRoute: typeof VariablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scopes': {
      id: '/scopes'
      path: '/scopes'
      fullPath: '/scopes'
      preLoaderRoute: typeof ScopesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tokens': {
      id: '/admin/tokens'
      path: '/admin/tokens'
      fullPath: '/admin/tokens'
      preLoaderRoute: typeof AdminTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/admin/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/admin/groups/': {
      id: '/admin/groups/'
      path: '/'
      fullPath: '/admin/groups/'
      preLoaderRoute: typeof AdminGroupsIndexRouteImport
      parentRoute: typeof AdminGroupsRoute
    }
    '/projects/group/$groupId': {
      id: '/projects/group/$groupId'
      path: '/projects/group/$groupId'
      fullPath: '/projects/group/$groupId'
      preLoaderRoute: typeof ProjectsGroupGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/snapshots': {
      id: '/projects/$projectId/snapshots'
      path: '/snapshots'
      fullPath: '/projects/$projectId/snapshots'
      preLoaderRoute: typeof ProjectsProjectIdSnapshotsRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/config': {
      id: '/projects/$projectId/config'
      path: '/config'
      fullPath: '/projects/$projectId/config'
      preLoaderRoute: typeof ProjectsProjectIdConfigRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/clients': {
      id: '/projects/$projectId/clients'
      path: '/clients'
      fullPath: '/projects/$projectId/clients'
      preLoaderRoute: typeof ProjectsProjectIdClientsRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/admin/groups/$groupId': {
      id: '/admin/groups/$groupId'
      path: '/$groupId'
      fullPath: '/admin/groups/$groupId'
      preLoaderRoute: typeof AdminGroupsGroupIdRouteImport
      parentRoute: typeof AdminGroupsRoute
    }
  }
}

interface ProjectsProjectIdRouteRouteChildren {
  ProjectsProjectIdClientsRoute: typeof ProjectsProjectIdClientsRoute
  ProjectsProjectIdConfigRoute: typeof ProjectsProjectIdConfigRoute
  ProjectsProjectIdSnapshotsRoute: typeof ProjectsProjectIdSnapshotsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteRouteChildren: ProjectsProjectIdRouteRouteChildren =
  {
    ProjectsProjectIdClientsRoute: ProjectsProjectIdClientsRoute,
    ProjectsProjectIdConfigRoute: ProjectsProjectIdConfigRoute,
    ProjectsProjectIdSnapshotsRoute: ProjectsProjectIdSnapshotsRoute,
    ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  }

const ProjectsProjectIdRouteRouteWithChildren =
  ProjectsProjectIdRouteRoute._addFileChildren(
    ProjectsProjectIdRouteRouteChildren,
  )

interface AdminGroupsRouteChildren {
  AdminGroupsGroupIdRoute: typeof AdminGroupsGroupIdRoute
  AdminGroupsIndexRoute: typeof AdminGroupsIndexRoute
}

const AdminGroupsRouteChildren: AdminGroupsRouteChildren = {
  AdminGroupsGroupIdRoute: AdminGroupsGroupIdRoute,
  AdminGroupsIndexRoute: AdminGroupsIndexRoute,
}

const AdminGroupsRouteWithChildren = AdminGroupsRoute._addFileChildren(
  AdminGroupsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  ClientsRoute: ClientsRoute,
  OverviewRoute: OverviewRoute,
  ScopesRoute: ScopesRoute,
  TemplatesRoute: TemplatesRoute,
  VariablesRoute: VariablesRoute,
  ProjectsProjectIdRouteRoute: ProjectsProjectIdRouteRouteWithChildren,
  AdminGroupsRoute: AdminGroupsRouteWithChildren,
  AdminTokensRoute: AdminTokensRoute,
  AdminUsersRoute: AdminUsersRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsGroupGroupIdRoute: ProjectsGroupGroupIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
