/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VariablesRouteImport } from './routes/variables'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ScopesRouteImport } from './routes/scopes'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTokensRouteImport } from './routes/admin/tokens'
import { Route as AdminGroupsRouteImport } from './routes/admin/groups'
import { Route as ProjectsProjectIdSnapshotsRouteImport } from './routes/projects/$projectId/snapshots'
import { Route as ProjectsProjectIdConfigRouteImport } from './routes/projects/$projectId/config'
import { Route as ProjectsProjectIdClientsRouteImport } from './routes/projects/$projectId/clients'

const VariablesRoute = VariablesRouteImport.update({
  id: '/variables',
  path: '/variables',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopesRoute = ScopesRouteImport.update({
  id: '/scopes',
  path: '/scopes',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTokensRoute = AdminTokensRouteImport.update({
  id: '/admin/tokens',
  path: '/admin/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/admin/groups',
  path: '/admin/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdSnapshotsRoute =
  ProjectsProjectIdSnapshotsRouteImport.update({
    id: '/projects/$projectId/snapshots',
    path: '/projects/$projectId/snapshots',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdConfigRoute = ProjectsProjectIdConfigRouteImport.update({
  id: '/projects/$projectId/config',
  path: '/projects/$projectId/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdClientsRoute =
  ProjectsProjectIdClientsRouteImport.update({
    id: '/projects/$projectId/clients',
    path: '/projects/$projectId/clients',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/overview': typeof OverviewRoute
  '/scopes': typeof ScopesRoute
  '/templates': typeof TemplatesRoute
  '/variables': typeof VariablesRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/users': typeof AdminUsersRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/clients': typeof ProjectsProjectIdClientsRoute
  '/projects/$projectId/config': typeof ProjectsProjectIdConfigRoute
  '/projects/$projectId/snapshots': typeof ProjectsProjectIdSnapshotsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/overview': typeof OverviewRoute
  '/scopes': typeof ScopesRoute
  '/templates': typeof TemplatesRoute
  '/variables': typeof VariablesRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/users': typeof AdminUsersRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/clients': typeof ProjectsProjectIdClientsRoute
  '/projects/$projectId/config': typeof ProjectsProjectIdConfigRoute
  '/projects/$projectId/snapshots': typeof ProjectsProjectIdSnapshotsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/overview': typeof OverviewRoute
  '/scopes': typeof ScopesRoute
  '/templates': typeof TemplatesRoute
  '/variables': typeof VariablesRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/users': typeof AdminUsersRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/clients': typeof ProjectsProjectIdClientsRoute
  '/projects/$projectId/config': typeof ProjectsProjectIdConfigRoute
  '/projects/$projectId/snapshots': typeof ProjectsProjectIdSnapshotsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/overview'
    | '/scopes'
    | '/templates'
    | '/variables'
    | '/admin/groups'
    | '/admin/tokens'
    | '/admin/users'
    | '/projects/'
    | '/projects/$projectId/clients'
    | '/projects/$projectId/config'
    | '/projects/$projectId/snapshots'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/overview'
    | '/scopes'
    | '/templates'
    | '/variables'
    | '/admin/groups'
    | '/admin/tokens'
    | '/admin/users'
    | '/projects'
    | '/projects/$projectId/clients'
    | '/projects/$projectId/config'
    | '/projects/$projectId/snapshots'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/overview'
    | '/scopes'
    | '/templates'
    | '/variables'
    | '/admin/groups'
    | '/admin/tokens'
    | '/admin/users'
    | '/projects/'
    | '/projects/$projectId/clients'
    | '/projects/$projectId/config'
    | '/projects/$projectId/snapshots'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  OverviewRoute: typeof OverviewRoute
  ScopesRoute: typeof ScopesRoute
  TemplatesRoute: typeof TemplatesRoute
  VariablesRoute: typeof VariablesRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminTokensRoute: typeof AdminTokensRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdClientsRoute: typeof ProjectsProjectIdClientsRoute
  ProjectsProjectIdConfigRoute: typeof ProjectsProjectIdConfigRoute
  ProjectsProjectIdSnapshotsRoute: typeof ProjectsProjectIdSnapshotsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/variables': {
      id: '/variables'
      path: '/variables'
      fullPath: '/variables'
      preLoaderRoute: typeof VariablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scopes': {
      id: '/scopes'
      path: '/scopes'
      fullPath: '/scopes'
      preLoaderRoute: typeof ScopesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tokens': {
      id: '/admin/tokens'
      path: '/admin/tokens'
      fullPath: '/admin/tokens'
      preLoaderRoute: typeof AdminTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/admin/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/snapshots': {
      id: '/projects/$projectId/snapshots'
      path: '/projects/$projectId/snapshots'
      fullPath: '/projects/$projectId/snapshots'
      preLoaderRoute: typeof ProjectsProjectIdSnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/config': {
      id: '/projects/$projectId/config'
      path: '/projects/$projectId/config'
      fullPath: '/projects/$projectId/config'
      preLoaderRoute: typeof ProjectsProjectIdConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/clients': {
      id: '/projects/$projectId/clients'
      path: '/projects/$projectId/clients'
      fullPath: '/projects/$projectId/clients'
      preLoaderRoute: typeof ProjectsProjectIdClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  OverviewRoute: OverviewRoute,
  ScopesRoute: ScopesRoute,
  TemplatesRoute: TemplatesRoute,
  VariablesRoute: VariablesRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminTokensRoute: AdminTokensRoute,
  AdminUsersRoute: AdminUsersRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdClientsRoute: ProjectsProjectIdClientsRoute,
  ProjectsProjectIdConfigRoute: ProjectsProjectIdConfigRoute,
  ProjectsProjectIdSnapshotsRoute: ProjectsProjectIdSnapshotsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
