using Microsoft.CodeAnalysis;

namespace GroundControl.Host.Api.Generators;

[Generator]
public class WebApiModuleGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("IWebApiModule.g.cs", IWebApiModuleSource);
            ctx.AddSource("IWebApiModule{TOptions}.g.cs", IWebApiModuleOfTOptionsSource);
            ctx.AddSource("RunsAfterAttribute.g.cs", RunsAfterAttributeSource);
            ctx.AddSource("RunsBeforeAttribute.g.cs", RunsBeforeAttributeSource);
            ctx.AddSource("ConfigurationKeyAttribute.g.cs", ConfigurationKeyAttributeSource);
        });
    }

    private const string IWebApiModuleSource =
        """
        // <auto-generated />
        #nullable enable

        namespace GroundControl.Host.Api;

        internal interface IWebApiModule
        {
            void OnServiceConfiguration(Microsoft.AspNetCore.Builder.WebApplicationBuilder builder);
            void OnApplicationConfiguration(Microsoft.AspNetCore.Builder.WebApplication app);
        }
        """;

    private const string IWebApiModuleOfTOptionsSource =
        """
        // <auto-generated />
        #nullable enable

        namespace GroundControl.Host.Api;

        internal interface IWebApiModule<TOptions> : IWebApiModule where TOptions : class, new()
        {
        }
        """;

    private const string RunsAfterAttributeSource =
        """
        // <auto-generated />
        #nullable enable

        namespace GroundControl.Host.Api;

        [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        internal sealed class RunsAfterAttribute<T> : System.Attribute where T : IWebApiModule
        {
            public bool Required { get; init; }
        }
        """;

    private const string RunsBeforeAttributeSource =
        """
        // <auto-generated />
        #nullable enable

        namespace GroundControl.Host.Api;

        [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
        internal sealed class RunsBeforeAttribute<T> : System.Attribute where T : IWebApiModule
        {
        }
        """;

    private const string ConfigurationKeyAttributeSource =
        """
        // <auto-generated />
        #nullable enable

        namespace GroundControl.Host.Api;

        [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
        internal sealed class ConfigurationKeyAttribute : System.Attribute
        {
            public ConfigurationKeyAttribute(string key) => Key = key;
            public string Key { get; }
        }
        """;
}
